export const SERVICE_CATEGORIES = [
  { id: 'study', label: '學習與課務', description: '查課表、整理學分，接續課堂上的事。' },
  { id: 'campus', label: '校園生活', description: '找教室、看公車，安排課堂以外的時間。' },
  { id: 'connect', label: '消息與交流', description: '看看校園近況，接收通知與朋友的訊息。' },
  { id: 'account', label: '帳號與協助', description: '管理個人資料，找到需要的協助。' },
] as const;

export type ServiceCategory = (typeof SERVICE_CATEGORIES)[number]['id'];

export const CAMPUS_SERVICES = [
  {
    name: '跨校交流',
    text: '在公開看板分享近況，認識其他校園的人',
    href: '/social',
    keywords: '社交 跨校 公開 看板 social',
    category: 'connect',
  },
  {
    name: '課表',
    text: '查看本人的課程時間與教室',
    href: '/timetable',
    keywords: '上課 行事曆 schedule',
    category: 'study',
  },
  {
    name: '成績',
    text: '查詢學校提供的學期成績',
    href: '/grades',
    keywords: '分數 學期 grade',
    category: 'study',
  },
  {
    name: '學分規劃',
    text: '依修課紀錄與自訂目標整理學分',
    href: '/credit-planner',
    keywords: '畢業 學分 credit',
    category: 'study',
  },
  {
    name: '課程與群組',
    text: '開啟已加入的課程，或使用邀請碼加入',
    href: '/groups',
    keywords: '作業 教材 教師 點名 course',
    category: 'study',
  },
  {
    name: '課程空間',
    text: '使用 Campus One 帳號閱讀教材、繳交作業與課堂作答',
    href: '/classroom',
    keywords: 'nuni 課程 教材 作業 測驗 classroom',
    category: 'study',
  },
  {
    name: '公告',
    text: '查詢校園公開公告',
    href: '/announcements',
    keywords: '消息 news',
    category: 'connect',
  },
  {
    name: '社團活動',
    text: '查看已加入的社團',
    href: '/clubs',
    keywords: '社團 club',
    category: 'campus',
  },
  {
    name: '通知',
    text: '查看本人收到的服務通知',
    href: '/messages',
    keywords: '提醒 notification',
    category: 'connect',
  },
  {
    name: '私訊',
    text: '接續已建立的對話',
    href: '/dms',
    keywords: '聊天 message',
    category: 'connect',
  },
  {
    name: '校園交流',
    text: '閱讀與分享校園話題',
    href: '/community',
    keywords: '貼文 社群 community',
    category: 'connect',
  },
  {
    name: '校園地圖',
    text: '查詢校內地點',
    href: '/map',
    keywords: '大樓 教室 位置 map',
    category: 'campus',
  },
  { name: '公車', text: '查詢路線與站牌', href: '/bus', keywords: '交通 bus', category: 'campus' },
  {
    name: '餐廳',
    text: '查看餐廳與菜單資料',
    href: '/cafeteria',
    keywords: '午餐 晚餐 餐點 food',
    category: 'campus',
  },
  {
    name: '店家合作',
    text: '申請進駐，查看審核進度與授權門市',
    href: '/merchant',
    keywords: '店家 商家 進駐 申請 審核 merchant',
    category: 'account',
  },
  {
    name: '圖書館',
    text: '搜尋館藏，前往本人借閱帳號',
    href: '/library',
    keywords: '書籍 借書 續借 library',
    category: 'campus',
  },
  {
    name: '校園助理',
    text: '詢問校園服務與課務問題',
    href: '/ai-assistant',
    keywords: '問答 assistant',
    category: 'account',
  },
  {
    name: '個人資料',
    text: '查看與更新你的校園個人資料',
    href: '/profile',
    keywords: '姓名 學號 科系 profile',
    category: 'account',
  },
  {
    name: '設定',
    text: '調整外觀、通知與個人資料',
    href: '/settings',
    keywords: '主題 帳號 個人資料 setting',
    category: 'account',
  },
];
